### ISSUE TITLE
Gamecube support

### ISSUE THREAD

**Issue by Danfun64** [dfrood/SA2SaveUtility#1]
While the ability to edit the 360 and PS3 versions of the Chao Garden data is cool, the ability to edit Gamecube data would be a lot more convenient due to the Dolphin emulator's portability.

**Comment by dfrood** [comment]
Thank you for the recommendation, I will 100% work on this. Support shouldn't be too much of an issue, I've just not had a chance to look at the GC save and how it's structured yet.

**Comment by dfrood** [comment]
Gamecube support is around 90% done, will likely have an updated version with gamecube support tonight or some time tomorrow.

**Comment by dfrood** [comment]
Complete! The tool can now edit and convert to/from gamecube saves.
Any problems, let me know.
